/**
 * Stage 6 — Review
 *
 * Generates a human-readable review report at pipeline/review/<featureId>.md.
 * The report surfaces:
 *   - Conflicting facts (need human resolution)
 *   - Open questions (NOT YET IMPLEMENTED or unclear items)
 *   - Low-confidence facts (need verification)
 *   - Source references for every issue
 *
 * This is a code-only stage — no LLM involved.
 */

import { kbFilePath, reviewFilePath, reviewDir } from "../config/index.js";
import { readJson, writeText, ensureDir } from "../utils/files.js";
import type { Fact, FeatureKnowledgeBase } from "../types/index.js";

function formatFact(f: Fact): string {
  return [
    `**[${f.id}]** ${f.label}`,
    `- Topic: \`${f.topic}\``,
    `- Status: \`${f.status}\` | Confidence: \`${f.confidence}\``,
    `- Source: \`${f.provenance.source_type}:${f.provenance.source_id}\``,
    `- Content: ${f.content}`,
  ].join("\n");
}

export async function generateReview(featureId: string): Promise<void> {
  console.log(`\n[Stage 6] Generating review report for feature: ${featureId}`);

  const knowledgeBase = await readJson<FeatureKnowledgeBase>(
    kbFilePath(featureId)
  );

  const lowConfidence = knowledgeBase.facts.filter(
    (f) => f.confidence === "low" && f.topic !== "open_question"
  );

  const lines: string[] = [
    `# Review Report — ${featureId}`,
    "",
    `> Generated by Pepper Soup on ${new Date().toLocaleString()}`,
    `> This file is a checklist for documentation reviewers before publishing.`,
    "",
    "---",
    "",
    `## Summary`,
    "",
    `| Category | Count |`,
    `|---|---|`,
    `| Total facts | ${knowledgeBase.facts.length} |`,
    `| Total examples | ${knowledgeBase.examples.length} |`,
    `| Open questions | ${knowledgeBase.openQuestions.length} |`,
    `| Conflicting facts | ${knowledgeBase.conflicts.length} |`,
    `| Low-confidence facts | ${lowConfidence.length} |`,
    "",
    "---",
    "",
  ];

  // Conflicting Facts
  if (knowledgeBase.conflicts.length > 0) {
    lines.push("## ⚠️ Conflicting Facts");
    lines.push("");
    lines.push(
      "> These facts were flagged as conflicting across sources. A human must resolve them before publishing."
    );
    lines.push("");
    for (const f of knowledgeBase.conflicts) {
      lines.push(formatFact(f));
      lines.push("");
    }
    lines.push("---");
    lines.push("");
  }

  // Open Questions
  if (knowledgeBase.openQuestions.length > 0) {
    lines.push("## ❓ Open Questions");
    lines.push("");
    lines.push(
      "> These items were explicitly marked as unresolved or not yet implemented."
    );
    lines.push("");
    for (const f of knowledgeBase.openQuestions) {
      lines.push(formatFact(f));
      lines.push("");
    }
    lines.push("---");
    lines.push("");
  }

  // Low-Confidence Facts
  if (lowConfidence.length > 0) {
    lines.push("## 🔍 Low-Confidence Facts");
    lines.push("");
    lines.push(
      "> These facts were inferred or were ambiguous in the source material. Please verify before publishing."
    );
    lines.push("");
    for (const f of lowConfidence) {
      lines.push(formatFact(f));
      lines.push("");
    }
    lines.push("---");
    lines.push("");
  }

  // All Sources
  const sourceIds = [
    ...new Set(knowledgeBase.facts.map((f) => f.provenance.source_id)),
  ];
  lines.push("## 📚 Source References");
  lines.push("");
  for (const sid of sourceIds) {
    const count = knowledgeBase.facts.filter(
      (f) => f.provenance.source_id === sid
    ).length;
    lines.push(`- \`${sid}\` — ${count} fact(s)`);
  }
  lines.push("");

  if (
    knowledgeBase.conflicts.length === 0 &&
    knowledgeBase.openQuestions.length === 0 &&
    lowConfidence.length === 0
  ) {
    lines.push(
      "> ✅ No conflicts, open questions, or low-confidence items found. Documentation looks clean!"
    );
  }

  const reportContent = lines.join("\n");
  await ensureDir(reviewDir());
  await writeText(reviewFilePath(featureId), reportContent);
}
